import type { Metadata } from "next";
import "./globals.css";
import poppins from "@/lib/fonts";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import SessionProviders from "@/components/provider/SessionProviders";
import ToastProvider from "@/components/provider/ToastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <ToastProvider>
      <SessionProviders>
        <Header />
          <div className="sm:h-[80vh]">
            {children}
          </div>
        <Footer />
      </SessionProviders>
      </ToastProvider>
      </body>
    </html>
  );
}
